//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrainManage.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrainManage.Web.Resources.GlobalResx", typeof(GlobalResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前页.
        /// </summary>
        public static string CurrentPage {
            get {
                return ResourceManager.GetString("CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy年MM月dd日.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.
        /// </summary>
        public static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中项.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑选中项.
        /// </summary>
        public static string EditSelected {
            get {
                return ResourceManager.GetString("EditSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 异常.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一页.
        /// </summary>
        public static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粮食管理.
        /// </summary>
        public static string GrainManage {
            get {
                return ResourceManager.GetString("GrainManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粮食管理系统.
        /// </summary>
        public static string GrainManageSystem {
            get {
                return ResourceManager.GetString("GrainManageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最后一页.
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载数据，请稍等....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粮食管理系统.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误消息.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多操作.
        /// </summary>
        public static string MoreAction {
            get {
                return ResourceManager.GetString("MoreAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一页.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共 {0} 页.
        /// </summary>
        public static string PageFormat {
            get {
                return ResourceManager.GetString("PageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一页.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元/千克 (yuan/kg).
        /// </summary>
        public static string PriceUnit1 {
            get {
                return ResourceManager.GetString("PriceUnit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元/斤 (yuan/500g).
        /// </summary>
        public static string PriceUnit2 {
            get {
                return ResourceManager.GetString("PriceUnit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;o1c0OH/qB2WK/y3Tvv841BAuwappxVDGaQgTCxFBCuYXXjXqp81s5/VBU        ///
        ///+vzPvFAGppnfJ1qnnyu5G4YeUEmCV0GsCfxoxNg91pxC7soUSI9aPL8CIO51DsPJujPSHi+1sOMjVKRkS3wvdyqGpNl591gEyvyc        ///
        ///+WYw6thgqQPDQM=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;0RP/DjGRc2S8ca4JuXDE1fy        ///
        ///+mejEpSZClWCq37nM8fcyoxULK7N4RYAg9pyXF2jrG3lX4lqHec347TYCuHRpYQ==&lt;/P&gt;&lt;Q&gt;x/9876VWk3mGgwXq6c5pyrCEZDec1oeESK2H1yjvqRkn59CydLU066gQaH        ///
        ///DvBcwMSHf+DVyrX/uAwH6qUK8c4w==&lt;/Q&gt;&lt;DP&gt;W7tcQov49xoRnAbx        ///
        ///+UzC7+gucDSyYotA121MS1Cn3NnKe8b12byqXkPzMoBNwlWkIa/BoWx62D [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;o1c0OH/qB2WK/y3Tvv841BAuwappxVDGaQgTCxFBCuYXXjXqp81s5/VBU        ///
        ///+vzPvFAGppnfJ1qnnyu5G4YeUEmCV0GsCfxoxNg91pxC7soUSI9aPL8CIO51DsPJujPSHi+1sOMjVKRkS3wvdyqGpNl591gEyvyc        ///
        ///+WYw6thgqQPDQM=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        public static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询系统.
        /// </summary>
        public static string QuerySystem {
            get {
                return ResourceManager.GetString("QuerySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求方式.
        /// </summary>
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求地址.
        /// </summary>
        public static string RequestUrl {
            get {
                return ResourceManager.GetString("RequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始搜索.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态码.
        /// </summary>
        public static string StatusCode {
            get {
                return ResourceManager.GetString("StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 千克 (kg).
        /// </summary>
        public static string WeightUnit1 {
            get {
                return ResourceManager.GetString("WeightUnit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 斤 (500g).
        /// </summary>
        public static string WeightUnit2 {
            get {
                return ResourceManager.GetString("WeightUnit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎来到.
        /// </summary>
        public static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
    }
}
