//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrainManage.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PriceResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PriceResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrainManage.Web.Resources.PriceResx", typeof(PriceResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有价格.
        /// </summary>
        public static string AllPrice {
            get {
                return ResourceManager.GetString("AllPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作物名称.
        /// </summary>
        public static string Grain {
            get {
                return ResourceManager.GetString("Grain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入作物名称.
        /// </summary>
        public static string GrainRequired {
            get {
                return ResourceManager.GetString("GrainRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建价格.
        /// </summary>
        public static string NewPrice {
            get {
                return ResourceManager.GetString("NewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格编号.
        /// </summary>
        public static string PriceID {
            get {
                return ResourceManager.GetString("PriceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格编号不能小于0.
        /// </summary>
        public static string PriceIDRanged {
            get {
                return ResourceManager.GetString("PriceIDRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入价格编号.
        /// </summary>
        public static string PriceIDRequired {
            get {
                return ResourceManager.GetString("PriceIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格类型.
        /// </summary>
        public static string PriceType {
            get {
                return ResourceManager.GetString("PriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入价格类型.
        /// </summary>
        public static string PriceTypeRequired {
            get {
                return ResourceManager.GetString("PriceTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新价格.
        /// </summary>
        public static string RecentPrice {
            get {
                return ResourceManager.GetString("RecentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索价格.
        /// </summary>
        public static string SearchPrice {
            get {
                return ResourceManager.GetString("SearchPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索最新价格.
        /// </summary>
        public static string SearchRecentPrice {
            get {
                return ResourceManager.GetString("SearchRecentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单价.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入单价.
        /// </summary>
        public static string UnitPriceRequired {
            get {
                return ResourceManager.GetString("UnitPriceRequired", resourceCulture);
            }
        }
    }
}
